00:
	python -m dictknife.swaggerknife.stream.jsonschema 00*.yaml
01:
	python -m dictknife.swaggerknife.stream.jsonschema 01*.yaml
02:
	python -m dictknife.swaggerknife.stream.jsonschema 02*.yaml
03:
	python -m dictknife.swaggerknife.stream.jsonschema 03*.yaml
