definitions:
  group:
    type: object
    properties:
      name:
        type: string
        example: foo
    required:
    - name
  person:
    type: object
    properties:
      name:
        type: string
        example: foo
      age:
        type: integer
        example: 20
      group:
        $ref: '#/definitions/group'
    required:
    - name
    - age
    - group
