components:
  parameters:
    userId:
      description: The ID of the user to return
      in: path
      name: userId
      required: true
      schema:
        format: int64
        minimum: 1
        type: integer
  requestBodies:
    postUserBody:
      content:
        application/json:
          schema:
            $ref: './definitions.yaml#/components/schemas/User'
      description: |
        The json body when creating user
      required: true
