info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
openapi: 3.0.0
servers:
- url: 'http://api.example.com/v1'
  description: ''
paths:
  /users:
    $ref: './api.yaml#/paths/~1users'
