info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
openapi: 3.0.0
servers:
- url: 'http://api.example.com/v1'
  description: ''
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      responses:
        200:
          description: A JSON array of user names
          schema:
            type: array
            items:
              type: string
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
