info:
  description: API description in Markdown.
  title: Sample API
  version: 1.0.0
openapi: 3.0.0
paths:
  /users:
    get:
      description: Optional extended description in Markdown.
      responses:
        '200':
          description: A JSON array of user names
          schema:
            items:
              type: string
            type: array
      summary: Returns a list of users.
servers:
- description: ''
  url: 'http://api.example.com/v1'
