components:
  securitySchemes:
    BasicAuth:
      type: basic
info:
  description: API description in Markdown.
  title: Sample API
  version: 1.0.0
openapi: 3.0.0
paths:
  /users:
    $ref: 'api_users.yaml#/paths/~1users'
  /users/{userId}:
    $ref: 'api_users.yaml#/paths/~1users~1{userId}'
  /users2:
    $ref: 'api_users2.yaml#/paths/~1users2'
  /users2/{userId}:
    $ref: 'api_users2.yaml#/paths/~1users2~1{userId}'
security:
- BasicAuth: []
servers:
- description: ''
  url: 'http://api.example.com/v1'
