swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - http
paths:
  /users:
    $ref: "./api.yaml#/paths/~1users"
