definitions:
  Schema:
    type: object
    properties:
      type:
        type: string
      patternProperties:
        type: object
        additionalProperties:
          oneOf:
          - {$ref: "#/definitions/Schema"}
          - {$ref: "Reference.yaml#/definitions/Reference"}
      properties:
        type: object
        patternProperties:
          "^[a-zA-Z0-9\\.\\-_]+$":
            oneOf:
            - {$ref: "#/definitions/Schema"}
            - {$ref: "Reference.yaml#/definitions/Reference"}
    required:
    - type
