default:
	@python -m dictknife.swaggerknife.stream.jsonschema separated/main.yaml --log=DEBUG 

00:
	@python -m dictknife.swaggerknife.stream.jsonschema examples/00*.yaml
01:
	@python -m dictknife.swaggerknife.stream.jsonschema examples/01*.yaml
02:
	@python -m dictknife.swaggerknife.stream.jsonschema examples/02*.yaml
03:
	@python -m dictknife.swaggerknife.stream.jsonschema examples/03*.yaml
