# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, synchronize, reopened ]  

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install make
      run: sudo apt-get install make
    - name: Install Hatch
      uses: pypa/hatch@install
    - name: unit test
      run: |
        hatch test -py ${{ matrix.python-version }}
    - name: lint
      run: |
        hatch run +py=${{ matrix.python-version }} e2e:check
    - name: e2e test
      run: |
        hatch env create "e2e.py${{ matrix.python-version }}"
        . "$(hatch env find "e2e.py${{ matrix.python-version }}")/bin/activate"
        python -V
        make ci
